// Chemistry — JAMB-style practice questions
// Format: { topic, q, options[4], correct (index), explain }
const CHEMISTRY_QUESTIONS = [

  // ===========================================================================
  // ─── 1. STOICHIOMETRY (50 QUESTIONS) ─────────────────────────────────────────
  // ===========================================================================

  // ─── STOICHIOMETRY: MOLE CONCEPT & AVOGADRO'S CONSTANT ─────────────────────
  {subject:"Chemistry",topic:"Stoichiometry",q:"What is the number of moles present in 36g of water, H₂O? [H=1, O=16]",options:["1 mol","2 mol","3 mol","4 mol"],correct:1,explain:"Molar mass of H₂O = 2(1) + 16 = 18g/mol. Moles = mass/molar mass = 36/18 = 2 mol."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many moles are present in 11.7g of sodium chloride, NaCl? [Na=23, Cl=35.5]",options:["0.1 mol","0.2 mol","0.5 mol","1.0 mol"],correct:1,explain:"Molar mass of NaCl = 23 + 35.5 = 58.5g/mol. Moles = 11.7/58.5 = 0.2 mol."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of carbon dioxide, CO₂, is contained in 0.5 mole of the gas? [C=12, O=16]",options:["11g","22g","44g","88g"],correct:1,explain:"Molar mass of CO₂ = 12 + 2(16) = 44g/mol. Mass = moles × molar mass = 0.5 × 44 = 22g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many molecules are present in 2 moles of oxygen gas, O₂? [Avogadro's constant = 6.02 × 10²³ mol⁻¹]",options:["3.01 × 10²³","6.02 × 10²³","1.204 × 10²⁴","2.408 × 10²⁴"],correct:2,explain:"Number of molecules = number of moles × Avogadro's constant = 2 × 6.02 × 10²³ = 1.204 × 10²⁴ molecules."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many atoms are present in 0.5 mole of sodium, Na? [Avogadro's constant = 6.02 × 10²³ mol⁻¹]",options:["1.204 × 10²⁴ atoms","6.02 × 10²³ atoms","3.01 × 10²³ atoms","1.505 × 10²³ atoms"],correct:2,explain:"Number of atoms = moles × Avogadro's constant = 0.5 × 6.02 × 10²³ = 3.01 × 10²³ atoms."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume will 2 moles of oxygen gas occupy at s.t.p? [G.M.V at s.t.p = 22.4dm³]",options:["11.2dm³","22.4dm³","44.8dm³","67.2dm³"],correct:2,explain:"At s.t.p, 1 mole of any gas occupies 22.4dm³. Therefore, 2 moles occupy 2 × 22.4 = 44.8dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many moles of nitrogen gas are present in 5.6dm³ of nitrogen at s.t.p? [G.M.V at s.t.p = 22.4dm³]",options:["0.1 mol","0.25 mol","0.5 mol","1 mol"],correct:1,explain:"At s.t.p, 1 mole of gas occupies 22.4dm³. Moles = volume/22.4 = 5.6/22.4 = 0.25 mol."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume at s.t.p is occupied by 16g of oxygen gas, O₂? [O=16, G.M.V at s.t.p = 22.4dm³]",options:["5.6dm³","11.2dm³","16.0dm³","22.4dm³"],correct:1,explain:"Molar mass of O₂ = 32g/mol. Moles = 16/32 = 0.5 mol. Volume = 0.5 × 22.4 = 11.2dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of oxygen gas, O₂, contains 3.01 × 10²³ molecules? [O=16, Avogadro's constant = 6.02 × 10²³ mol⁻¹]",options:["8g","16g","32g","64g"],correct:1,explain:"3.01 × 10²³ molecules represents 0.5 mole because 1 mole contains 6.02 × 10²³ molecules. Molar mass of O₂ = 32g/mol. Mass = 0.5 × 32 = 16g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many molecules are present in 9g of water, H₂O? [H=1, O=16, Avogadro's constant = 6.02 × 10²³ mol⁻¹]",options:["1.505 × 10²³","3.01 × 10²³","6.02 × 10²³","9.03 × 10²³"],correct:1,explain:"Molar mass of H₂O = 18g/mol. Moles = 9/18 = 0.5 mol. Number of molecules = 0.5 × 6.02 × 10²³ = 3.01 × 10²³ molecules."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many moles of oxygen molecules, O₂, are present in 6.4g of oxygen gas? [O=16]",options:["0.1 mol","0.2 mol","0.4 mol","0.8 mol"],correct:1,explain:"Molar mass of O₂ = 32g/mol. Moles = mass/molar mass = 6.4/32 = 0.2 mol."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many molecules are present in 4.4g of carbon (IV) oxide, CO₂? [C=12, O=16, Avogadro's number = 6.02×10²³ mol⁻¹]",options:["6.02×10²¹ molecules","6.02×10²² molecules","6.02×10²³ molecules","1.204×10²³ molecules"],correct:1,explain:"Molar mass of CO₂ = 44g/mol. Moles = 4.4/44 = 0.1 mol. Number of molecules = 0.1 × 6.02×10²³ = 6.02×10²²."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"2.0dm³ of a gas at s.t.p has a mass of 3.93g. Calculate the relative molecular mass of the gas. [G.M.V at s.t.p = 22.4dm³]",options:["22","32","44","64"],correct:2,explain:"Moles = 2.0/22.4 ≈ 0.0893 mol. Molar mass = mass/moles = 3.93/0.0893 ≈ 44."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many total chlorine atoms are present in 0.1 mole of chlorine gas, Cl₂? [Avogadro's constant = 6.02 × 10²³ mol⁻¹]",options:["6.02 × 10²²","1.204 × 10²³","6.02 × 10²³","1.204 × 10²⁴"],correct:1,explain:"1 mole of Cl₂ contains 2 moles of Cl atoms. Moles of Cl atoms = 0.1 × 2 = 0.2 mol. Number of atoms = 0.2 × 6.02 × 10²³ = 1.204 × 10²³."},

  // ─── STOICHIOMETRY: BASIC REACTION STOICHIOMETRY ────────────────────────────
  {subject:"Chemistry",topic:"Stoichiometry",q:"According to the equation 2H₂ + O₂ → 2H₂O, how many moles of water are produced when 3 moles of hydrogen react completely with excess oxygen?",options:["1 mol","2 mol","3 mol","6 mol"],correct:2,explain:"The mole ratio H₂ : H₂O is 2:2, or 1:1. Therefore, 3 moles of H₂ produce 3 moles of H₂O."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"In the reaction 2Mg + O₂ → 2MgO, what mass of magnesium oxide is produced when 4.8g of magnesium reacts completely with excess oxygen? [Mg=24, O=16]",options:["4.0g","8.0g","12.0g","16.0g"],correct:1,explain:"Moles of Mg = 4.8/24 = 0.2 mol. The mole ratio Mg : MgO is 1:1, so 0.2 mol Mg produces 0.2 mol MgO. Molar mass of MgO = 24 + 16 = 40g/mol. Mass = 0.2 × 40 = 8.0g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"Calcium carbonate decomposes according to the equation CaCO₃ → CaO + CO₂. What mass of carbon dioxide is produced from 10g of CaCO₃? [Ca=40, C=12, O=16]",options:["2.2g","4.4g","5.6g","10g"],correct:1,explain:"Molar mass of CaCO₃ = 100g/mol. Moles of CaCO₃ = 10/100 = 0.1 mol. The ratio CaCO₃ : CO₂ is 1:1, so 0.1 mol CO₂ is produced. Molar mass of CO₂ = 44g/mol. Mass = 0.1 × 44 = 4.4g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"In the reaction N₂ + 3H₂ → 2NH₃, how many moles of ammonia are produced from 2 moles of nitrogen when hydrogen is in excess?",options:["1 mol","2 mol","4 mol","6 mol"],correct:2,explain:"The equation shows that 1 mole of N₂ produces 2 moles of NH₃. Therefore, 2 moles of N₂ produce 2 × 2 = 4 moles of NH₃."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of water is produced when 4g of hydrogen gas burns completely in excess oxygen? [H=1, O=16] (2H₂ + O₂ → 2H₂O)",options:["18g","24g","36g","72g"],correct:2,explain:"Moles of H₂ = 4/2 = 2 mol. The mole ratio H₂ : H₂O is 1:1, so 2 mol H₂ produces 2 mol H₂O. Molar mass of H₂O = 18g/mol. Mass = 2 × 18 = 36g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume of oxygen gas at s.t.p is required to react completely with 4.48dm³ of hydrogen gas according to 2H₂ + O₂ → 2H₂O?",options:["1.12dm³","2.24dm³","4.48dm³","8.96dm³"],correct:1,explain:"At the same temperature and pressure, gas volumes react in the ratio of their coefficients. H₂ : O₂ = 2:1. Therefore, oxygen required = 4.48 × 1/2 = 2.24dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"According to the equation CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂, how many moles of hydrochloric acid are required to react completely with 0.5 mole of CaCO₃?",options:["0.25 mol","0.5 mol","1.0 mol","2.0 mol"],correct:2,explain:"The mole ratio CaCO₃ : HCl is 1:2. Therefore, 0.5 mole of CaCO₃ requires 0.5 × 2 = 1.0 mole of HCl."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of sodium chloride is produced when 4.6g of sodium reacts completely with excess chlorine gas? [Na=23, Cl=35.5] (2Na + Cl₂ → 2NaCl)",options:["5.85g","11.7g","23.4g","58.5g"],correct:1,explain:"Moles of Na = 4.6/23 = 0.2 mol. The mole ratio Na : NaCl is 1:1, so 0.2 mol NaCl is produced. Molar mass of NaCl = 58.5g/mol. Mass = 0.2 × 58.5 = 11.7g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume of carbon dioxide at s.t.p is produced when 10g of calcium carbonate reacts completely with excess hydrochloric acid? [Ca=40, C=12, O=16, G.M.V at s.t.p = 22.4dm³]",options:["1.12dm³","2.24dm³","4.48dm³","22.4dm³"],correct:1,explain:"Molar mass of CaCO₃ = 100g/mol. Moles of CaCO₃ = 10/100 = 0.1 mol. The mole ratio CaCO₃ : CO₂ is 1:1, so 0.1 mol CO₂ is produced. Volume = 0.1 × 22.4 = 2.24dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"In the reaction 2Al + 6HCl → 2AlCl₃ + 3H₂, what volume of hydrogen gas at s.t.p is produced from 5.4g of aluminium? [Al=27, G.M.V at s.t.p = 22.4dm³]",options:["2.24dm³","4.48dm³","6.72dm³","8.96dm³"],correct:2,explain:"Moles of Al = 5.4/27 = 0.2 mol. From the equation, 2 mol Al produces 3 mol H₂. Therefore, moles H₂ = 0.2 × 3/2 = 0.3 mol. Volume = 0.3 × 22.4 = 6.72dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of calcium oxide, CaO, is produced when 20g of calcium carbonate, CaCO₃, is completely decomposed by heat? [Ca=40, C=12, O=16]",options:["5.6g","11.2g","22.4g","44.8g"],correct:1,explain:"CaCO₃ → CaO + CO₂. Molar mass of CaCO₃ = 100g/mol, CaO = 56g/mol. Moles of CaCO₃ = 20/100 = 0.2 mol → produces 0.2 mol CaO = 0.2 × 56 = 11.2g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many moles of hydrogen gas are produced when 4.6g of sodium reacts completely with excess water? [Na=23] (2Na + 2H₂O → 2NaOH + H₂)",options:["0.1 mol","0.2 mol","0.4 mol","0.05 mol"],correct:0,explain:"Moles of Na = 4.6/23 = 0.2 mol. From the equation, 2 mol Na produces 1 mol H₂, so 0.2 mol Na produces 0.1 mol H₂."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"In the reaction N₂ + 3H₂ → 2NH₃, what volume of ammonia is formed from 30cm³ of hydrogen gas, assuming all volumes are measured at the same temperature and pressure?",options:["10cm³","15cm³","20cm³","30cm³"],correct:2,explain:"Mole ratio H₂ : NH₃ = 3 : 2. So volume of NH₃ = (2/3) × 30 = 20cm³. Gas volumes react in the same ratio as their moles."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume of carbon (IV) oxide, measured at s.t.p, is produced when 5g of calcium trioxocarbonate (IV), CaCO₃, reacts completely with excess dilute hydrochloric acid? [Ca=40, C=12, O=16, G.M.V at s.t.p = 22.4dm³]",options:["560cm³","1120cm³","2240cm³","5600cm³"],correct:1,explain:"CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. Molar mass CaCO₃ = 100g/mol. Moles = 5/100 = 0.05 mol → 0.05 mol CO₂ → volume = 0.05 × 22400cm³ = 1120cm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of water is produced when 8.0g of hydrogen gas is completely burnt in excess oxygen? [H=1, O=16] (2H₂ + O₂ → 2H₂O)",options:["36g","72g","144g","18g"],correct:1,explain:"Moles H₂ = 8.0/2 = 4 mol. The mole ratio H₂ : H₂O is 1:1, so moles H₂O = 4 mol. Mass = 4 × 18 = 72g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume of hydrogen gas, measured at s.t.p, is liberated when 5.4g of aluminium reacts completely with excess dilute tetraoxosulphate (VI) acid? [Al=27, G.M.V at s.t.p=22.4dm³] (2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂)",options:["3.36dm³","4.48dm³","6.72dm³","8.96dm³"],correct:2,explain:"Moles Al = 5.4/27 = 0.2 mol. Mole ratio Al : H₂ is 2:3, so moles H₂ = 0.2 × 3/2 = 0.3 mol. Volume = 0.3 × 22.4 = 6.72dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What mass of iron (III) oxide, Fe₂O₃, would be required to produce 11.2g of iron by reduction with excess carbon monoxide? [Fe=56, O=16] (Fe₂O₃ + 3CO → 2Fe + 3CO₂)",options:["8g","16g","32g","48g"],correct:1,explain:"Molar mass Fe₂O₃ = 160g/mol. Moles Fe = 11.2/56 = 0.2 mol. Mole ratio Fe₂O₃ : Fe is 1:2, so moles Fe₂O₃ = 0.1 mol. Mass = 0.1 × 160 = 16g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"Determine the mass of potassium trioxochlorate (V), KClO₃, needed to produce 3.36dm³ of oxygen gas at s.t.p on heating. [K=39, Cl=35.5, O=16, G.M.V at s.t.p=22.4dm³] (2KClO₃ → 2KCl + 3O₂)",options:["6.125g","12.25g","24.5g","36.75g"],correct:1,explain:"Moles O₂ = 3.36/22.4 = 0.15 mol. Mole ratio KClO₃ : O₂ is 2:3, so moles KClO₃ = 0.15 × 2/3 = 0.1 mol. Molar mass KClO₃ = 122.5g/mol. Mass = 0.1 × 122.5 = 12.25g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"5.6g of iron reacts completely with excess dilute hydrochloric acid. What volume of hydrogen gas is liberated at s.t.p? [Fe=56, G.M.V at s.t.p=22.4dm³] (Fe + 2HCl → FeCl₂ + H₂)",options:["1.12dm³","2.24dm³","4.48dm³","11.2dm³"],correct:1,explain:"Moles Fe = 5.6/56 = 0.1 mol. The mole ratio Fe : H₂ is 1:1, so moles H₂ = 0.1 mol. Volume = 0.1 × 22.4 = 2.24dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"Determine the volume of carbon (IV) oxide produced at s.t.p when 2.4g of carbon is completely burned in excess oxygen. [C=12, G.M.V at s.t.p = 22.4dm³]",options:["2.24dm³","4.48dm³","8.96dm³","11.20dm³"],correct:1,explain:"C + O₂ → CO₂. Moles C = 2.4/12 = 0.2 mol. Ratio C : CO₂ is 1:1, so 0.2 mol CO₂ is produced. Volume = 0.2 × 22.4 = 4.48dm³."},

  // ─── STOICHIOMETRY: LIMITING REAGENTS, YIELD & PURITY ──────────────────────
  {subject:"Chemistry",topic:"Stoichiometry",q:"What is the percentage yield of a reaction if the theoretical yield of a product is 50g but only 37.5g was actually obtained?",options:["60%","70%","75%","80%"],correct:2,explain:"% yield = (actual/theoretical) × 100 = (37.5/50) × 100 = 75%."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"2.4g of magnesium is reacted with 3.65g of hydrochloric acid. Mg + 2HCl → MgCl₂ + H₂. Which reagent is present in excess, and by how many moles? [Mg=24, H=1, Cl=35.5]",options:["HCl in excess by 0.05 mol","Mg in excess by 0.05 mol","HCl in excess by 0.1 mol","Mg in excess by 0.1 mol"],correct:1,explain:"Moles Mg = 2.4/24 = 0.1 mol (needs 0.2 mol HCl to react fully). Moles HCl available = 3.65/36.5 = 0.1 mol, which is only enough to react with 0.05 mol Mg. So HCl is the limiting reagent, and Mg is in excess by 0.1 − 0.05 = 0.05 mol."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"A sample of impure calcium trioxocarbonate (IV) weighing 12.5g was heated and produced 4.4g of carbon (IV) oxide. Calculate the percentage purity of the sample. [Ca=40, C=12, O=16] (CaCO₃ → CaO + CO₂)",options:["60%","70%","80%","90%"],correct:2,explain:"Moles CO₂ = 4.4/44 = 0.1 mol, so moles CaCO₃ reacted = 0.1 mol (1:1 ratio). Mass of pure CaCO₃ = 0.1 × 100 = 10g. Percentage purity = 10/12.5 × 100 = 80%."},

  // ─── STOICHIOMETRY: EMPIRICAL & MOLECULAR FORMULAS ─────────────────────────
  {subject:"Chemistry",topic:"Stoichiometry",q:"Calculate the empirical formula of a compound containing 40% carbon, 6.7% hydrogen, and 53.3% oxygen by mass. [C=12, H=1, O=16]",options:["CHO","CH₂O","C₂H₄O₂","CH₃O"],correct:1,explain:"Divide by molar mass: C = 40/12 = 3.33, H = 6.7/1 = 6.7, O = 53.3/16 = 3.33. Divide through by smallest: C=1, H=2, O=1 → CH₂O."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"A hydrocarbon contains 85.7% carbon and 14.3% hydrogen by mass. What is its empirical formula? [C=12, H=1]",options:["CH","CH₂","CH₃","C₂H₅"],correct:1,explain:"C: 85.7/12 = 7.14, H: 14.3/1 = 14.3. Divide by the smaller value (7.14): C = 1, H ≈ 2. Empirical formula = CH₂."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"A hydrated salt, MgSO₄·xH₂O, has a molar mass of 246g/mol. Determine the value of x. [Mg=24, S=32, O=16, H=1]",options:["5","6","7","10"],correct:2,explain:"Molar mass of anhydrous MgSO₄ = 24+32+64 = 120g/mol. Mass of water of crystallization = 246 − 120 = 126g. Since each H₂O = 18g/mol, x = 126/18 = 7."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"Determine the percentage by mass of nitrogen in ammonium trioxonitrate (V), NH₄NO₃. [N=14, H=1, O=16]",options:["17.5%","28%","35%","43.75%"],correct:2,explain:"Molar mass of NH₄NO₃ = 14+4+14+48 = 80g/mol. Total mass of nitrogen (two N atoms) = 28g. Percentage = 28/80 × 100 = 35%."},

  // ─── STOICHIOMETRY: VOLUMETRIC ANALYSIS & SOLUTIONS ────────────────────────
  {subject:"Chemistry",topic:"Stoichiometry",q:"4.9g of tetraoxosulphate (VI) acid, H₂SO₄, is dissolved in water to make 250cm³ of solution. What is the molar concentration of the solution? [H=1, S=32, O=16]",options:["0.1 mol/dm³","0.2 mol/dm³","0.4 mol/dm³","0.5 mol/dm³"],correct:1,explain:"Molar mass of H₂SO₄ = 98g/mol. Moles = 4.9/98 = 0.05 mol. Concentration = moles/volume(dm³) = 0.05/0.25 = 0.2 mol/dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"50cm³ of 0.2mol/dm³ hydrochloric acid exactly neutralizes 25cm³ of a sodium hydroxide solution. What is the concentration of the sodium hydroxide solution? (HCl + NaOH → NaCl + H₂O)",options:["0.2 mol/dm³","0.4 mol/dm³","0.5 mol/dm³","0.8 mol/dm³"],correct:1,explain:"Moles HCl = 0.050dm³ × 0.2mol/dm³ = 0.01 mol. Since the mole ratio is 1:1, moles NaOH = 0.01 mol. Concentration = 0.01/0.025 = 0.4 mol/dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"0.4g of a monobasic acid requires 20cm³ of 0.25mol/dm³ NaOH solution for complete neutralization. Calculate the molar mass of the acid.",options:["40g/mol","60g/mol","80g/mol","100g/mol"],correct:2,explain:"Moles NaOH = 0.020dm³ × 0.25mol/dm³ = 0.005 mol. Since the acid is monobasic (1:1 ratio), moles of acid = 0.005 mol. Molar mass = 0.4/0.005 = 80g/mol."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"5.85g of sodium chloride, NaCl, is dissolved in water to make 500cm³ of solution. What is the molar concentration of the solution? [Na=23, Cl=35.5]",options:["0.1 mol/dm³","0.2 mol/dm³","0.4 mol/dm³","1.0 mol/dm³"],correct:1,explain:"Molar mass of NaCl = 58.5g/mol. Moles = 5.85/58.5 = 0.1 mol. Concentration = 0.1/0.5 = 0.2 mol/dm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"What volume of 0.1 mol/dm³ HCl is required to neutralize 25cm³ of 0.2 mol/dm³ Na₂CO₃ solution?",options:["25cm³","50cm³","100cm³","200cm³"],correct:2,explain:"Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂. Moles Na₂CO₃ = 0.025 × 0.2 = 0.005 mol. Moles HCl required = 2 × 0.005 = 0.01 mol. Volume HCl = 0.01 / 0.1 = 0.1 dm³ = 100cm³."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"Calculate the mass of anhydrous sodium trioxocarbonate (IV) needed to prepare 500cm³ of a 0.1 mol/dm³ solution. [Na=23, C=12, O=16]",options:["2.65g","5.30g","10.60g","21.20g"],correct:1,explain:"Molar mass Na₂CO₃ = 2(23) + 12 + 3(16) = 106g/mol. Moles = 0.5dm³ × 0.1mol/dm³ = 0.05 mol. Mass = 0.05 × 106 = 5.30g."},

  // ─── STOICHIOMETRY: FARADAY'S LAWS OF ELECTROLYSIS ─────────────────────────
  {subject:"Chemistry",topic:"Stoichiometry",q:"Calculate the mass of silver deposited when a steady current of 2A is passed through a solution of silver trioxonitrate (V) for 965 seconds. [Ag=108, 1 Faraday = 96500C]",options:["1.08g","2.16g","4.32g","0.54g"],correct:1,explain:"Quantity of electricity, Q = It = 2 × 965 = 1930C. Moles of electrons = 1930/96500 = 0.02 mol. Since Ag⁺ + e⁻ → Ag, moles of Ag = 0.02 mol, so mass = 0.02 × 108 = 2.16g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"Calculate the mass of copper deposited when a current of 5A is passed through a solution of copper (II) tetraoxosulphate (VI) for 3860 seconds. [Cu=64, 1 Faraday=96500C]",options:["3.2g","6.4g","12.8g","19.2g"],correct:1,explain:"Quantity of electricity, Q = It = 5 × 3860 = 19300C. Moles of electrons = 19300/96500 = 0.2 mol. Since Cu²⁺ + 2e⁻ → Cu, moles of Cu = 0.2/2 = 0.1 mol. Mass = 0.1 × 64 = 6.4g."},
  {subject:"Chemistry",topic:"Stoichiometry",q:"How many moles of electrons are required to deposit 1 mole of aluminium from molten aluminium oxide by electrolysis? (Al³⁺ + 3e⁻ → Al)",options:["1","2","3","4"],correct:2,explain:"The half-equation Al³⁺ + 3e⁻ → Al shows that 3 moles of electrons are needed to deposit 1 mole of aluminium atoms."},


  // ===========================================================================
  // ─── 2. GAS LAWS (50 QUESTIONS) ─────────────────────────────────────────────
  // ===========================================================================

  // ─── GAS LAWS: BOYLE'S, CHARLES' & GAY-LUSSAC'S LAWS ───────────────────────
  {subject:"Chemistry",topic:"Gas Laws",q:"A gas occupies 400cm³ at 27°C. What volume will it occupy at 127°C if pressure is kept constant?",options:["300cm³","400cm³","533cm³","600cm³"],correct:2,explain:"Charles' Law: V₁/T₁ = V₂/T₂. In Kelvin: T₁=300K, T₂=400K. V₂ = (400 × 400)/300 = 533cm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A fixed mass of gas at a pressure of 2 atm occupies 6dm³. What volume will it occupy if the pressure is increased to 4 atm at constant temperature?",options:["2dm³","3dm³","4dm³","12dm³"],correct:1,explain:"Boyle's Law: P₁V₁ = P₂V₂. (2×6) = (4×V₂) → V₂ = 12/4 = 3dm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A gas occupies a volume of 250cm³ at a pressure of 1.5atm. What pressure would be required to compress it to 150cm³ at constant temperature?",options:["1.5atm","2.0atm","2.5atm","3.0atm"],correct:2,explain:"Boyle's Law: P₁V₁ = P₂V₂. P₂ = (1.5 × 250)/150 = 375/150 = 2.5atm."},
  {subject:"Chemistry",topic:"Gas Laws",q:"At what temperature (in °C) will 300cm³ of gas at 27°C and constant pressure expand to 500cm³?",options:["127°C","227°C","327°C","500°C"],correct:1,explain:"Charles' Law: V₁/T₁ = V₂/T₂. T₁ = 300K. T₂ = 300 × 500/300 = 500K = (500 − 273)°C = 227°C."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A fixed volume of gas has a pressure of 2atm at 300K. What will its pressure be if the temperature is raised to 450K at constant volume?",options:["1.5atm","2atm","3atm","4.5atm"],correct:2,explain:"By the Pressure (Gay-Lussac's) Law, P₁/T₁ = P₂/T₂. P₂ = 2 × 450/300 = 3atm."},
  {subject:"Chemistry",topic:"Gas Laws",q:"If the volume of a fixed mass of gas is halved while the temperature is kept constant, the pressure of the gas will:",options:["double","halve","remain the same","quadruple"],correct:0,explain:"By Boyle's Law, pressure and volume are inversely proportional at constant temperature, so halving the volume doubles the pressure."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A gas at 500K occupying 400cm³ is cooled at constant pressure until its volume becomes 200cm³. What is the final temperature?",options:["100K","150K","250K","1000K"],correct:2,explain:"Charles' Law: V₁/T₁ = V₂/T₂. T₂ = T₁ × V₂/V₁ = 500 × 200/400 = 250K."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A syringe contains 20cm³ of air at a pressure of 1atm. If the plunger is pushed in until the volume is 5cm³ at constant temperature, what is the new pressure?",options:["0.25atm","2atm","4atm","5atm"],correct:2,explain:"Boyle's Law: P₂ = P₁V₁/V₂ = (1 × 20)/5 = 4atm."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Which graphical plot illustrates an inverse proportion relationship according to Boyle's Law?",options:["P against V","P against 1/V","V against T (°C)","PV against P"],correct:1,explain:"By Boyle's Law, pressure is inversely proportional to volume (P ∝ 1/V). Plotting P against 1/V yields a straight line passing through the origin."},
  {subject:"Chemistry",topic:"Gas Laws",q:"What is the absolute zero of temperature in degrees Celsius?",options:["0°C","-100°C","-273°C","-373°C"],correct:2,explain:"Absolute zero on the Kelvin scale is 0 K, which corresponds to -273.15°C (commonly -273°C in JAMB calculations)."},
  {subject:"Chemistry",topic:"Gas Laws",q:"If a gas occupies 100cm³ at 27°C, at what temperature will its volume double at constant pressure?",options:["54°C","300°C","327°C","600°C"],correct:2,explain:"T₁ = 27 + 273 = 300K. By Charles' Law, doubling volume doubles absolute temperature: T₂ = 600K. T₂ in °C = 600 - 273 = 327°C."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Which parameter is held constant in Charles' Law?",options:["Volume","Temperature","Pressure","Number of moles and pressure"],correct:3,explain:"Charles' Law evaluates the relationship between volume and absolute temperature for a fixed mass of gas at constant pressure."},
  {subject:"Chemistry",topic:"Gas Laws",q:"The volume of a gas is inversely proportional to its pressure at constant temperature. This statement is known as:",options:["Charles' Law","Boyle's Law","Gay-Lussac's Law","Graham's Law"],correct:1,explain:"Boyle's Law explicitly states that volume and pressure are inversely proportional for a fixed mass of gas at constant temperature."},

  // ─── GAS LAWS: COMBINED & IDEAL GAS EQUATIONS ─────────────────────────────
  {subject:"Chemistry",topic:"Gas Laws",q:"What volume does 0.5 mole of an ideal gas occupy at standard temperature and pressure (S.T.P)?",options:["5.6dm³","11.2dm³","22.4dm³","44.8dm³"],correct:1,explain:"At STP, 1 mole of any gas occupies 22.4dm³. So 0.5 mol occupies 0.5 × 22.4 = 11.2dm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A gas occupies 400cm³ at a pressure of 760mmHg and a temperature of 300K. What volume will it occupy at 380mmHg and 450K?",options:["600cm³","900cm³","1200cm³","1500cm³"],correct:2,explain:"Combined gas law: P₁V₁/T₁ = P₂V₂/T₂. V₂ = (P₁V₁T₂)/(P₂T₁) = (760×400×450)/(380×300) = 136,800,000/114,000 = 1200cm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Calculate the number of moles of a gas that occupies 4.1dm³ at a pressure of 2atm and a temperature of 300K. [R = 0.082 dm³atm/mol·K]",options:["0.17 mol","0.33 mol","0.5 mol","1.0 mol"],correct:1,explain:"Using the ideal gas equation, n = PV/RT = (2 × 4.1)/(0.082 × 300) = 8.2/24.6 ≈ 0.33 mol."},
  {subject:"Chemistry",topic:"Gas Laws",q:"1.1g of a gas occupies 560cm³ at s.t.p. Calculate its relative molecular mass. [G.M.V at s.t.p = 22400cm³]",options:["22","32","44","58"],correct:2,explain:"Moles = 560/22400 = 0.025 mol. Molar mass = mass/moles = 1.1/0.025 = 44."},
  {subject:"Chemistry",topic:"Gas Laws",q:"What is the mass of 5.6dm³ of ammonia gas, NH₃, measured at s.t.p? [N=14, H=1, G.M.V at s.t.p=22.4dm³]",options:["2.125g","4.25g","8.5g","17g"],correct:1,explain:"Moles = 5.6/22.4 = 0.25 mol. Molar mass of NH₃ = 17g/mol. Mass = 0.25 × 17 = 4.25g."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A fixed mass of gas occupies 2dm³ at a pressure of 3atm and temperature 250K. What pressure would it exert if compressed to 1dm³ at 500K?",options:["6atm","9atm","12atm","15atm"],correct:2,explain:"Combined gas law: P₁V₁/T₁ = P₂V₂/T₂. P₂ = (P₁V₁T₂)/(T₁V₂) = (3×2×500)/(250×1) = 3000/250 = 12atm."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Calculate the volume occupied at s.t.p by 8.5g of ammonia gas, NH₃. [N=14, H=1, G.M.V at s.t.p=22.4dm³]",options:["5.6dm³","11.2dm³","22.4dm³","44.8dm³"],correct:1,explain:"Molar mass of NH₃ = 17g/mol. Moles = 8.5/17 = 0.5 mol. Volume = 0.5 × 22.4 = 11.2dm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Using the ideal gas equation, calculate the volume occupied by 0.5 mole of a gas at a pressure of 1atm and a temperature of 273K. [R=0.082 dm³atm/mol·K]",options:["5.6dm³","11.2dm³","22.4dm³","44.8dm³"],correct:1,explain:"V = nRT/P = (0.5 × 0.082 × 273)/1 ≈ 11.2dm³ — as expected, close to the molar volume of a gas at s.t.p."},
  {subject:"Chemistry",topic:"Gas Laws",q:"2.8dm³ of a gas at s.t.p has a mass of 5.5g. What is the molar mass of the gas? [G.M.V at s.t.p=22.4dm³]",options:["22","32","44","55"],correct:2,explain:"Moles = 2.8/22.4 = 0.125 mol. Molar mass = mass/moles = 5.5/0.125 = 44."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Standard temperature and pressure (S.T.P) refers to:",options:["0°C and 1 atmosphere (760mmHg)","25°C and 1 atmosphere","0°C and 2 atmospheres","100°C and 760mmHg"],correct:0,explain:"S.T.P is conventionally defined as 0°C (273K) and 1 atmosphere pressure (760mmHg), the reference conditions for the molar gas volume of 22.4dm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"What is the molar mass of a gas if 0.56dm³ of it measured at s.t.p has a mass of 1.6g? [G.M.V at s.t.p = 22.4dm³]",options:["32 g/mol","44 g/mol","64 g/mol","80 g/mol"],correct:2,explain:"Moles = 0.56 / 22.4 = 0.025 mol. Molar mass = Mass / Moles = 1.6 / 0.025 = 64 g/mol."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Calculate the density of oxygen gas (in g/dm³) at s.t.p. [O=16, G.M.V at s.t.p = 22.4dm³]",options:["0.71 g/dm³","1.43 g/dm³","2.86 g/dm³","3.20 g/dm³"],correct:1,explain:"Density = Molar mass / Molar volume. Molar mass of O₂ = 32g. Density = 32 / 22.4 ≈ 1.43 g/dm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A gas occupies 500cm³ at 27°C and 700mmHg. What volume will it occupy at s.t.p?",options:["418.6 cm³","455.0 cm³","500.0 cm³","546.0 cm³"],correct:0,explain:"Combined gas law: P₁V₁/T₁ = P₂V₂/T₂. (700 × 500)/300 = (760 × V₂)/273. V₂ = (700 × 500 × 273)/(300 × 760) = 418.6 cm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"What volume does 11g of CO₂ occupy at s.t.p? [C=12, O=16, G.M.V at s.t.p = 22.4dm³]",options:["2.8 dm³","5.6 dm³","11.2 dm³","22.4 dm³"],correct:1,explain:"Molar mass CO₂ = 44 g/mol. Moles = 11 / 44 = 0.25 mol. Volume = 0.25 × 22.4 = 5.6 dm³."},
  {subject:"Chemistry",topic:"Gas Laws",q:"In the ideal gas equation PV = nRT, what are the standard units for R when P is in atmospheres and V is in dm³?",options:["J/mol·K","dm³·atm/mol·K","cal/mol·K","Pa·m³/mol·K"],correct:1,explain:"When pressure is given in atm, volume in dm³ (or liters), and temperature in Kelvin, the gas constant R uses dm³·atm/mol·K (0.0821)."},

  // ─── GAS LAWS: GRAHAM'S LAW & VAPOUR DENSITY ───────────────────────────────
  {subject:"Chemistry",topic:"Gas Laws",q:"40cm³ of gas A diffuses through a porous plug in 20 seconds. Gas B takes 40 seconds for the same volume under the same conditions. If molar mass of A is 16, what is the molar mass of B?",options:["4","32","64","8"],correct:2,explain:"Graham's Law: rate ∝ 1/√M. Rate A = 2, Rate B = 1. 2/1 = √(Mᴃ/16) → 4 = Mᴃ/16 → Mᴃ = 64."},
  {subject:"Chemistry",topic:"Gas Laws",q:"What is the vapour density of a gas whose molar mass is 44g/mol?",options:["11","22","44","88"],correct:1,explain:"Vapour density = molar mass ÷ 2 (since hydrogen, the reference gas, has a molar mass of 2). VD = 44/2 = 22."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Gas P has a density four times that of gas Q at the same temperature and pressure. How do their rates of diffusion compare?",options:["P diffuses twice as fast as Q","Q diffuses twice as fast as P","P diffuses four times as fast as Q","They diffuse at the same rate"],correct:1,explain:"By Graham's Law, rate ∝ 1/√density. RateP/RateQ = √(densityQ/densityP) = √(1/4) = 1/2. So Q diffuses twice as fast as P."},
  {subject:"Chemistry",topic:"Gas Laws",q:"60cm³ of oxygen diffuses through a porous plug in 40 seconds. How long will it take 60cm³ of hydrogen to diffuse through the same plug under identical conditions? [O₂=32, H₂=2]",options:["5s","10s","20s","160s"],correct:1,explain:"By Graham's Law, rate(H₂)/rate(O₂) = √(32/2) = √16 = 4, so hydrogen diffuses 4 times as fast as oxygen. Time for H₂ = 40/4 = 10s."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Which of the following gases will diffuse fastest at the same temperature and pressure? [H₂=2, CH₄=16, N₂=28, CO₂=44]",options:["H₂","CH₄","N₂","CO₂"],correct:0,explain:"By Graham's Law, the lightest gas diffuses fastest, since rate is inversely proportional to the square root of molar mass. H₂ has the lowest molar mass."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Calculate the ratio of the rate of diffusion of hydrogen gas to that of oxygen gas under the same conditions. [H=1, O=16]",options:["2:1","4:1","8:1","16:1"],correct:1,explain:"By Graham's Law, rate(H₂)/rate(O₂) = √(molar mass O₂/molar mass H₂) = √(32/2) = √16 = 4. So the ratio is 4:1."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Calculate the relative rate of diffusion of methane (CH₄) compared to sulphur (IV) oxide (SO₂). [C=12, H=1, S=32, O=16]",options:["1 : 2","2 : 1","1 : 4","4 : 1"],correct:1,explain:"Molar mass CH₄ = 16, SO₂ = 64. Rate(CH₄)/Rate(SO₂) = √(64/16) = √4 = 2. Methane diffuses twice as fast as SO₂."},
  {subject:"Chemistry",topic:"Gas Laws",q:"What is the vapour density of a triatomic gas with a relative molecular mass of 48?",options:["12","16","24","48"],correct:2,explain:"Vapour density = Relative Molecular Mass / 2. VD = 48 / 2 = 24."},
  {subject:"Chemistry",topic:"Gas Laws",q:"How long will it take 100cm³ of oxygen gas to diffuse through a porous plug if 100cm³ of hydrogen gas diffuses through the same plug in 5 seconds? [H=1, O=16]",options:["10 seconds","20 seconds","40 seconds","80 seconds"],correct:1,explain:"Rate is inversely proportional to time. t(O₂)/t(H₂) = √(M(O₂)/M(H₂)) = √(32/2) = √16 = 4. t(O₂) = 5 × 4 = 20 seconds."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A gas diffuses 1.414 times faster than gas X. If the molar mass of the gas is 16, what is the molar mass of gas X?",options:["8","32","48","64"],correct:1,explain:"Rate / Rate_X = √(M_X / M). 1.414 = √(M_X / 16). Squaring both sides: 2 = M_X / 16 → M_X = 32."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Which gas among the following will diffuse slowest at a given temperature? [H=1, C=12, N=14, O=16, S=32]",options:["NH₃","CO₂","SO₂","CH₄"],correct:2,explain:"By Graham's Law, the gas with the highest molar mass diffuses slowest. SO₂ = 64, CO₂ = 44, NH₃ = 17, CH₄ = 16."},

  // ─── GAS LAWS: DALTON'S LAW OF PARTIAL PRESSURES ──────────────────────────
  {subject:"Chemistry",topic:"Gas Laws",q:"A mixture of gases contains 2 moles of N₂, 3 moles of O₂ and 5 moles of CO₂ at a total pressure of 100kPa. What is the partial pressure of the oxygen?",options:["20kPa","30kPa","50kPa","60kPa"],correct:1,explain:"By Dalton's Law, partial pressure = mole fraction × total pressure. Mole fraction of O₂ = 3/10 = 0.3. Partial pressure = 0.3 × 100kPa = 30kPa."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A container holds a mixture of gases with partial pressures: nitrogen 40kPa, oxygen 25kPa, and carbon (IV) oxide 15kPa. What is the total pressure of the mixture?",options:["65kPa","70kPa","80kPa","90kPa"],correct:2,explain:"By Dalton's Law of Partial Pressures, the total pressure is the sum of the individual partial pressures: 40 + 25 + 15 = 80kPa."},
  {subject:"Chemistry",topic:"Gas Laws",q:"A sample of gas collected over water at 27°C and 750mmHg total pressure has a volume of 200cm³. If the saturated vapour pressure of water at 27°C is 20mmHg, what is the pressure of the dry gas?",options:["730mmHg","750mmHg","770mmHg","720mmHg"],correct:0,explain:"By Dalton's Law of Partial Pressures, P_total = P_dry gas + P_water vapour. P_dry gas = 750 - 20 = 730mmHg."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Two non-reacting gases A and B are mixed in a vessel. If the mole fraction of gas A is 0.4 and the total pressure is 500 mmHg, what is the partial pressure of gas B?",options:["200 mmHg","250 mmHg","300 mmHg","400 mmHg"],correct:2,explain:"Mole fraction of B = 1 - 0.4 = 0.6. Partial pressure of B = 0.6 × 500 = 300 mmHg."},

  // ─── GAS LAWS: AVOGADRO'S & GAY-LUSSAC'S COMBINING VOLUMES ────────────────
  {subject:"Chemistry",topic:"Gas Laws",q:"Which gas law states that equal volumes of all gases, at the same temperature and pressure, contain equal numbers of molecules?",options:["Boyle's Law","Charles' Law","Avogadro's Law","Graham's Law"],correct:2,explain:"Avogadro's Law relates volume directly to moles of gas at constant T and P — the basis for molar volume (22.4dm³ at STP)."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Equal volumes of carbon (IV) oxide and nitrogen gas under the same conditions of temperature and pressure contain the same number of:",options:["Atoms","Molecules","Electrons","Protons"],correct:1,explain:"Avogadro's Law states that equal volumes of all gases under identical conditions contain equal numbers of molecules."},
  {subject:"Chemistry",topic:"Gas Laws",q:"According to Gay-Lussac's Law of Combining Volumes, what volume of oxygen at s.t.p is required to completely burn 20cm³ of carbon (II) oxide?",options:["10cm³","20cm³","30cm³","40cm³"],correct:0,explain:"2CO + O₂ → 2CO₂. The mole/volume ratio of CO : O₂ is 2 : 1. Volume of O₂ = 20 / 2 = 10cm³."},

  // ─── GAS LAWS: IDEAL VS. REAL GASES ───────────────────────────────────────
  {subject:"Chemistry",topic:"Gas Laws",q:"Real gases deviate most from ideal gas behaviour under conditions of:",options:["high temperature and low pressure","low temperature and high pressure","high temperature and high pressure","low temperature and low pressure"],correct:1,explain:"At low temperature and high pressure, gas particles are forced close together, making intermolecular forces and the particles' finite volume significant — causing deviation from ideal behaviour."},
  {subject:"Chemistry",topic:"Gas Laws",q:"Under what conditions of temperature and pressure do real gases deviate most from ideal gas behavior?",options:["High temperature and high pressure","Low temperature and high pressure","High temperature and low pressure","Low temperature and low pressure"],correct:1,explain:"At low temperatures, particle kinetic energy drops so intermolecular forces become significant. At high pressures, the volume of the particles themselves cannot be ignored."},


  // ===========================================================================
  // ─── 3. KINETIC THEORY OF MATTER (50 QUESTIONS) ────────────────────────────
  // ===========================================================================

  // ─── KINETIC THEORY: POSTULATES, MOTION & ELASTIC COLLISIONS ─────────────
  {subject:"Chemistry",topic:"Kinetic Theory",q:"According to the kinetic theory of matter, particles in a gas are best described as having:",options:["Fixed positions with strong forces of attraction","Vibratory motion only, close together","Random, rapid motion with negligible forces of attraction between particles","No motion at all"],correct:2,explain:"In gases, particles are far apart, move randomly and rapidly, and have very weak forces of attraction — explaining compressibility and expansion."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following best explains why a gas exerts pressure on the walls of its container, according to kinetic theory?",options:["Gas particles are attracted to the walls","Gas particles collide with the walls of the container","Gas particles have fixed positions near the walls","The walls push against the gas"],correct:1,explain:"Pressure arises from continuous, random collisions of fast-moving gas particles with the container walls, transferring momentum."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Why does increasing the temperature of a gas (at constant volume) increase its pressure, according to kinetic theory?",options:["The particles become larger","The number of particles increases","Particles move faster and collide with the container walls more frequently and forcefully","The particles stop moving"],correct:2,explain:"Raising temperature increases average kinetic energy, so particles move faster, increasing both frequency and force of collisions with the walls."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following is NOT a postulate of the kinetic theory of gases?",options:["Gas particles are in constant random motion","Collisions between gas particles are perfectly elastic","There are strong forces of attraction between gas particles","The volume of the gas particles themselves is negligible compared to the container volume"],correct:2,explain:"Kinetic theory assumes forces of attraction between gas particles are negligible, not strong — this is what allows gases to expand freely and fill any container."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"According to kinetic theory, the temperature of a gas is a measure of:",options:["the pressure exerted by the gas","the average kinetic energy of the gas particles","the volume occupied by the gas","the mass of the gas particles"],correct:1,explain:"Temperature is directly related to the average kinetic energy of particles — higher temperature means particles move faster on average."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"According to kinetic theory, when a gas is compressed at constant temperature, its pressure increases mainly because:",options:["the particles increase in size","the particles collide with the walls of the container more frequently due to reduced volume","the particles slow down","the number of particles increases"],correct:1,explain:"Compressing a gas reduces the space available, so particles hit the container walls more often in a given time, increasing pressure — while their speed (and hence kinetic energy) is unchanged at constant temperature."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The average kinetic energy of the particles of a gas is directly proportional to:",options:["the pressure of the gas","the volume of the gas","the absolute (Kelvin) temperature of the gas","the density of the gas"],correct:2,explain:"Kinetic theory states that the average kinetic energy of gas particles depends only on the absolute temperature — not on pressure, volume, or the identity of the gas."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"As a gas is cooled towards absolute zero (0K), what happens to the kinetic energy of its particles, according to kinetic theory?",options:["It increases indefinitely","It approaches a minimum, theoretically zero","It remains constant","It becomes negative"],correct:1,explain:"Absolute zero is defined as the theoretical temperature at which particles have the minimum possible kinetic energy, approaching zero motion."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The pressure exerted by a fixed mass of gas in a sealed, rigid container will increase if:",options:["the temperature of the gas is decreased","the volume of the container is increased","the temperature of the gas is increased","some of the gas is removed"],correct:2,explain:"Increasing temperature increases the average kinetic energy of the particles, so they move faster and collide with the container walls more frequently and forcefully, raising the pressure."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"In the kinetic theory of matter, the term 'elastic collision' means that when gas particles collide:",options:["they stick together","there is no net loss of kinetic energy in the system","they slow down permanently","they release heat energy that is lost from the system"],correct:1,explain:"An elastic collision conserves the total kinetic energy of the colliding particles — none is lost as heat or sound, even though individual particles may speed up or slow down."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"A fixed mass of gas is heated at constant pressure. According to kinetic theory, what happens to the average distance between its particles?",options:["It decreases","It increases, as the particles move faster and spread further apart, increasing the volume","It remains constant","It becomes zero"],correct:1,explain:"At constant pressure, heating a gas increases particle speed; to keep the pressure constant, the gas expands, so the average distance between particles increases (Charles' Law)."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"According to kinetic theory, why is a gas easily compressible while a solid is not?",options:["Gas particles are much larger than solid particles","There is a large amount of empty space between gas particles, unlike in solids where particles are closely packed","Gas particles have no mass","Solid particles repel each other strongly"],correct:1,explain:"Gas particles are far apart with mostly empty space between them, so reducing the volume just pushes them closer together. Solid particles are already tightly packed, leaving little room for further compression."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The root-mean-square velocity of gas molecules is directly proportional to:",options:["Square root of absolute temperature","Absolute temperature","Square of absolute temperature","Molar mass"],correct:0,explain:"Kinetic molecular theory establishes that molecular velocity v_rms is proportional to √(T/M)."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"What happens to the average kinetic energy of gas molecules when the absolute temperature is halved?",options:["It doubles","It stays the same","It is halved","It drops to zero"],correct:2,explain:"Average kinetic energy is directly proportional to absolute (Kelvin) temperature ($KE \\propto T$)."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which postulate of the kinetic molecular theory fails for real gases under high pressure?",options:["Gas particles are in continuous random motion","Collisions are elastic","The volume of individual gas particles is negligible compared to container volume","Average kinetic energy depends on temperature"],correct:2,explain:"At high pressure, total gas volume decreases, making the physical volume of the molecules significant."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which statement accurately describes an elastic collision between gas molecules?",options:["Molecules stick together after impact","Total kinetic energy is conserved","Kinetic energy is converted to light","The molecules lose momentum"],correct:1,explain:"In elastic collisions, no net loss of total translational kinetic energy occurs across colliding bodies."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"At absolute zero (0 K or -273°C), kinetic molecular theory assumes that:",options:["Gas pressure reaches infinity","Molecular motion theoretically ceases","Gases expand indefinitely","Gas particles decompose"],correct:1,explain:"Absolute zero represents the thermal state where translational molecular motion drops to its theoretical minimum (zero)."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"When a gas is heated at constant volume, its pressure increases because:",options:["Gas particles expand","Particle collisions with the container walls become more frequent and energetic","Intermolecular forces increase","The density of the gas increases"],correct:1,explain:"Increasing temperature increases particle kinetic energy, raising both the collision frequency and impulse delivered to container walls."},

  // ─── KINETIC THEORY: STATES OF MATTER & PHASE TRANSITIONS ──────────────────
  {subject:"Chemistry",topic:"Kinetic Theory",q:"As a solid is heated and changes to a liquid, what happens to the kinetic energy and arrangement of its particles?",options:["Kinetic energy decreases; particles move further apart","Kinetic energy increases; particles gain enough energy to overcome some forces of attraction and move more freely","Kinetic energy stays constant; particles remain fixed","Kinetic energy increases; particles bond more tightly together"],correct:1,explain:"Heating increases particle kinetic energy. In melting, particles gain enough energy to partially overcome intermolecular forces and move more freely."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"In which state of matter are the particles arranged in a regular, closely packed pattern with strong forces of attraction between them?",options:["Gas","Liquid","Solid","Plasma"],correct:2,explain:"In solids, particles are held in fixed, orderly positions by strong intermolecular forces, only vibrating about fixed points."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which state of matter has particles with the greatest average distance between them?",options:["Solid","Liquid","Gas","Plasma"],correct:2,explain:"Gas particles are far apart with negligible forces of attraction, giving them the greatest average separation of the common states of matter."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The change of a substance directly from the solid state to the gaseous state, without passing through the liquid state, is called:",options:["Evaporation","Condensation","Sublimation","Melting"],correct:2,explain:"Sublimation is the direct solid-to-gas transition, occurring when particles gain enough energy to escape the solid lattice directly as a gas — e.g. iodine or solid CO₂."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following statements about the kinetic theory of matter is TRUE for liquids?",options:["Particles are far apart with negligible forces of attraction","Particles are held in fixed positions and only vibrate","Particles are close together, can move past one another, with moderate forces of attraction","Particles have no kinetic energy"],correct:2,explain:"In liquids, particles are close together like in solids but have enough energy to slide past one another, held by moderate (weaker than solid) forces of attraction."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following best explains why solids do not flow like liquids or gases?",options:["Solid particles have no kinetic energy","Solid particles are held in fixed positions by strong forces of attraction, only vibrating about a mean position","Solid particles move freely and randomly","Solid particles repel one another strongly"],correct:1,explain:"In solids, strong intermolecular forces lock particles into fixed positions in a lattice; they can only vibrate in place, so the solid keeps a definite shape and cannot flow."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following correctly ranks the three common states of matter in order of INCREASING force of attraction between particles?",options:["Solid < Liquid < Gas","Gas < Liquid < Solid","Liquid < Gas < Solid","Solid < Gas < Liquid"],correct:1,explain:"Forces of attraction are weakest in gases (particles far apart), stronger in liquids, and strongest in solids (particles locked in a fixed lattice)."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"When a solid melts, the temperature remains constant until all the solid has transformed into liquid. This absorbed heat is used to:",options:["Increase kinetic energy of particles","Overcome intermolecular forces holding the lattice","Break covalent bonds within molecules","Decrease potential energy"],correct:1,explain:"Latent heat of fusion absorbed during melting goes into breaking down the rigid solid crystal lattice (overcoming intermolecular forces) rather than raising particle kinetic energy, so temperature stays constant."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which state transition corresponds to condensation?",options:["Solid to liquid","Liquid to gas","Gas to liquid","Solid to gas"],correct:2,explain:"Condensation is the physical phase transition of a substance from the gaseous (vapour) phase into the liquid phase."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which state of matter exhibits fixed volume but variable shape?",options:["Solid","Liquid","Gas","Plasma"],correct:1,explain:"Liquids have definite volume due to cohesive forces, but take the shape of their container because particles can slide past each other."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The process in which a gas changes directly into a solid without becoming a liquid is known as:",options:["Sublimation","Deposition","Condensation","Freezing"],correct:1,explain:"Deposition (or desublimation) is the direct phase transition from gas to solid."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Compared to gases, liquids are virtually incompressible because:",options:["Liquid particles have higher mass","Particles in liquids are packed closely with minimal intermolecular space","Liquids have stronger covalent bonds","Liquid particles do not move"],correct:1,explain:"Minimal free space exists between closely packed liquid molecules, resisting volume reduction under pressure."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"When water freezes at 0°C, its density decreases because:",options:["Molecules lose mass","An open, hydrogen-bonded hexagonal crystal lattice forms","Kinetic energy increases","Hydrogen bonds break down entirely"],correct:1,explain:"Freezing locks water molecules into an open hexagonal lattice stabilized by hydrogen bonds, expanding volume and decreasing density."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"What term describes the direct transition of solid iodine or ammonium chloride into gas upon heating?",options:["Distillation","Evaporation","Sublimation","Crystallization"],correct:2,explain:"Sublimation is the direct conversion of solid to gas without entering the liquid state."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which property allows liquids to flow and take the shape of their container while retaining fixed volume?",options:["Rigid crystal lattice","Weak intermolecular forces allowing sliding movement","Negligible density","Elastic particle collisions"],correct:1,explain:"Intermediate cohesive forces hold particles together while permitting fluid translation across neighboring molecules."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which process represents an endothermic phase change?",options:["Condensation","Freezing","Vaporization","Deposition"],correct:2,explain:"Vaporization requires thermal energy input to overcome liquid cohesive forces."},

  // ─── KINETIC THEORY: PHENOMENA SUPPORTING KINETIC THEORY ────────────────────
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Brownian motion, observed as the random, erratic movement of smoke particles in air, provides evidence for which idea?",options:["Gas particles are stationary","Gas particles are in continuous, random motion and collide with larger particles","Gas particles have no mass","Gas particles only move in straight lines without colliding"],correct:1,explain:"Brownian motion is direct evidence for kinetic theory: erratic movement of visible smoke particles results from collisions with fast, invisible gas molecules."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The fact that a gas diffuses to fill any container it is placed in, regardless of shape, is best explained by which feature of kinetic theory?",options:["Gas particles have negligible volume","Gas particles are in continuous random motion with negligible attractive forces between them","Gas particles collide elastically","Gas particles have high density"],correct:1,explain:"Because gas particles move randomly and are barely attracted to one another, they spread out to occupy all available space — this is diffusion."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following provides the best evidence that gas particles are in constant, random motion?",options:["Diffusion of gases","Melting of ice","Boiling of water","Sublimation of iodine"],correct:0,explain:"Diffusion — the spontaneous spreading and mixing of gases — happens only because gas particles are in continuous, random motion, without any need for stirring."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Two gas jars — one containing reddish-brown bromine vapour, the other air — are connected and left undisturbed. After some time, the reddish-brown colour spreads evenly through both jars. This observation illustrates:",options:["Effusion","Diffusion","Osmosis","Sublimation"],correct:1,explain:"This is diffusion: the random motion of bromine particles causes them to spread from a region of high concentration to low concentration until evenly mixed, with no external stirring."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following gases would you expect to diffuse fastest, based on kinetic theory and molar mass? [He=4, N₂=28, O₂=32, CO₂=44]",options:["He","N₂","O₂","CO₂"],correct:0,explain:"At a given temperature, lighter particles move faster on average (since kinetic energy ½mv² is the same for all gases at that temperature). Helium, being lightest, diffuses fastest."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which of the following is an application of the kinetic theory of matter in everyday life?",options:["The inflation of a car tyre with air","The use of a thermometer to measure temperature","The smell of perfume spreading across a room","All of the above"],correct:3,explain:"All three rely on kinetic theory: tyre inflation depends on particle collisions creating pressure, thermometers respond to changes in average kinetic energy, and perfume spreading is diffusion."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which process demonstrates the phenomenon of diffusion in liquids?",options:["Melting of ice in water","Spreading of a drop of ink in a beaker of water","Boiling of water","Formation of frost"],correct:1,explain:"The spontaneous spreading and mixing of ink particles throughout liquid water without stirring is direct evidence of diffusion in liquids."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which phenomenon provides macroscopic evidence for the particulate nature of matter and molecular collisions?",options:["Tyndall effect","Brownian motion","Electrolysis","Neutralization"],correct:1,explain:"Brownian motion (erratic movement of suspended particles) direct proves incessant collisions with surrounding moving molecules."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Diffusion occurs fastest in which state of matter?",options:["Solid","Liquid","Gas","Plasma"],correct:2,explain:"Gaseous particles have high velocities, large mean free paths, and negligible attractive forces, facilitating fast diffusion."},

  // ─── KINETIC THEORY: EVAPORATION, VAPOUR PRESSURE & BOILING ────────────────
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Evaporation causes cooling of a liquid because:",options:["only the fastest-moving, most energetic particles escape the surface, lowering the average kinetic energy of the particles left behind","the liquid loses mass","the liquid's particles stop moving entirely","the surrounding air becomes colder first"],correct:0,explain:"Evaporation removes the highest-energy particles from the surface, leaving behind particles with lower average kinetic energy — which is a lower temperature."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The kinetic theory explains that increasing the temperature of a liquid increases its rate of evaporation because:",options:["more particles gain enough kinetic energy to overcome the forces of attraction and escape the surface","the liquid's volume decreases","the particles stop attracting one another completely","the surface area of the liquid decreases"],correct:0,explain:"Higher temperature raises the average kinetic energy of the liquid's particles, so a greater fraction have enough energy to break free from the surface as vapour."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Why do liquids evaporate faster at higher temperatures?",options:["A larger fraction of molecules possess sufficient kinetic energy to escape the liquid surface","Intermolecular forces increase with temperature","The surface tension of the liquid increases","Liquid particles stop colliding"],correct:0,explain:"Increasing temperature shifts the molecular energy distribution, so more surface molecules gain enough kinetic energy to overcome attractive forces and escape as vapour."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"The temperature at which the vapour pressure of a liquid equals atmospheric pressure is called its:",options:["Melting point","Freezing point","Normal boiling point","Critical temperature"],correct:2,explain:"By definition, boiling occurs when a liquid's internal vapour pressure equals surrounding external atmospheric pressure."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Surface tension in liquids is caused by:",options:["Unbalanced downward attractive forces acting on surface molecules","Evaporation at the surface","High molecular speed","Viscous friction"],correct:0,explain:"Surface molecules experience net inward cohesive pull from below and beside, creating a stretched elastic membrane behavior."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Which factor decreases the rate of evaporation of a liquid in an open container?",options:["Increase in surface area","Increase in temperature","Increase in atmospheric humidity","Passing dry air over the surface"],correct:2,explain:"High humidity saturates air above the liquid, increasing condensation rate back into the liquid and lowering net evaporation rate."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Why does volatile ether feel cold when spilled on skin?",options:["Ether reacts chemically with skin","Ether absorbs latent heat of vaporization from skin to evaporate","Ether transfers heat into skin","Ether freezes skin cells on contact"],correct:1,explain:"Evaporation requires energy; volatile liquids draw latent heat of vaporization from surroundings (skin), creating a cooling effect."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Saturated vapour pressure of a liquid depends ONLY on:",options:["Volume of liquid","Surface area of container","Temperature","Atmospheric pressure"],correct:2,explain:"Saturated vapour pressure is a temperature-dependent property governed by particle kinetic energy."},
  {subject:"Chemistry",topic:"Kinetic Theory",q:"Boiling point elevation occurs when a non-volatile solute is added to a solvent because the solute:",options:["Raises the liquid's vapour pressure","Lowers the liquid's vapour pressure","Increases solvent kinetic energy","Destroys solvent hydrogen bonds"],correct:1,explain:"Solute particles at the surface decrease solvent evaporation rate, lowering vapour pressure and requiring higher temperatures to reach atmospheric pressure."}
];
